rule Eden_Variant_Artifacts {
    meta:
        description = "Detects artifacts generated by Eden's Sins polymorphic engine"
        author = "The Eden's Sins Team"
        reference = "https://github.com/m4rba4s/Edem-Sins"
        date = "2026-02-17"
        tlp = "WHITE"

    strings:
        // NOP sled patterns specific to crates/arch/x86_64.rs
        // 9-byte NOP: 66 0F 1F 84 00 00 00 00 00
        $nop9 = { 66 0F 1F 84 00 00 00 00 00 }
        
        // 8-byte NOP: 0F 1F 84 00 00 00 00 00
        $nop8 = { 0F 1F 84 00 00 00 00 00 }
        
        // 7-byte NOP: 0F 1F 80 00 00 00 00
        $nop7 = { 0F 1F 80 00 00 00 00 }
        
        // 6-byte NOP: 66 0F 1F 44 00 00
        $nop6 = { 66 0F 1F 44 00 00 }

        // Codec specific encoding quirks?
        // E.g. Zero RAX => 48 31 C0 (REX.W + XOR) is less common than 31 C0
        $zero_rax_rex = { 48 31 C0 }
        
        // Mov r64, 0 used as Zero
        $mov_rax_0 = { B8 00 00 00 00 00 00 00 00 }

    condition:
        // High density of specific multi-byte NOPs indicates Morphogen layout
        3 of ($nop*) or
        // Unusual zeroing idioms combined with NOPs
        (all of ($zero*) and 1 of ($nop*))
}

rule Eden_High_Entropy_Blocks {
    meta:
        description = "Detects high entropy code blocks characteristic of packed/polymorphic payloads"
        
    condition:
        // This requires external module 'math' usually available in YARA
        math.entropy(0, filesize) >= 5.5 and math.entropy(0, filesize) <= 6.5
}
